# Generated by Django 5.1.4 on 2025-01-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewhistory",
            name="job_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
