# Generated by Django 5.1.4 on 2025-01-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
