# Generated by Django 5.1.4 on 2025-01-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate_profiles", "0002_interviewhistory_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewhistory",
            name="interview_date",
            field=models.DateTimeField(),
        ),
    ]
