# Generated by Django 5.1.4 on 2025-01-06 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        ("jobposts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewPreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        default=list, help_text="A list of technical questions."
                    ),
                ),
                (
                    "interview_duration",
                    models.PositiveIntegerField(
                        help_text="Duration of the interview in minutes."
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "job_post",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Tie this preparation to a specific job post.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_preparations",
                        to="jobposts.jobpost",
                    ),
                ),
            ],
        ),
    ]
