# Generated by Django 5.1.4 on 2025-01-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_interviewpreparation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationrubric",
            name="scoring_guide",
            field=models.TextField(
                help_text='Guide for scoring based on this criterion (e.g., "Excellent: Clear and concise answer").'
            ),
        ),
    ]
