"""
Django migration for the JobPost model.

This migration creates the `JobPost` model, which represents job postings
with fields for title, company name, location, employment type, description,
responsibilities, requirements, benefits, and application deadline. It also
includes metadata such as creation and update timestamps and establishes
a foreign key relationship with the User model for the author.

Generated by Django 5.1.4 on 2025-01-02 20:57.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration for creating the JobPost model.

    This class defines the migration for the `JobPost` model, including
    the initial schema setup. The model contains fields for job-related
    information, metadata for ordering, and a foreign key linking to the
    User model as the author.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FT", "Full-time"),
                            ("PT", "Part-time"),
                            ("CT", "Contract"),
                            ("IN", "Internship"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField()),
                ("responsibilities", models.TextField()),
                ("requirements", models.TextField()),
                ("benefits", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("application_deadline", models.DateField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on", "author"],
            },
        ),
    ]
