# Generated by Django 5.1.4 on 2025-01-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employer_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="company_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
