# Generated by Django 5.1.4 on 2025-01-19 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employer_profiles", "0003_interviewfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewfeedback",
            name="overall_score",
            field=models.IntegerField(
                blank=True,
                help_text="Overall score between 0 and 100.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="interviewfeedback",
            name="recommendation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
